---
title: "stuff"
format: html
---

ALL I DO IS MAKE QUARTO DOCUMENTS

```{r}
library(tidyverse)
alllll <- read.csv("voiceSauce.csv", header = TRUE, check.names = FALSE)
```

```{r}
knitr::opts_chunk$set(dev = "png",
                      dpi = 600,
                      fig.width=14,
                      fig.height =22,
                      echo = TRUE,
                      cache = TRUE)

all_data %>% 
  mutate(Language = language) %>% 
  ggplot(aes(x = Phonation, fill = Phonation)) +
  geom_bar() +
  guides(fill="none")

alllll %>% 
  mutate(Language = language) %>% 
  mutate(Phonation = phonation) %>% 
  ggplot(aes(x = Phonation, fill = Phonation)) +
  geom_bar() +
  guides(fill="none")
```


```{r}
knitr::opts_chunk$set(dev = "png",
                      dpi = 600,
                      fig.width=14,
                      fig.height =22,
                      echo = TRUE,
                      cache = TRUE)

all_data <- all_data %>% 
  # mutate(CQ = CQ_H) %>% 
  mutate(Phonation = phonation)

plottydata %>% 
  ggplot(aes(y = CQ, x = Phonation)) +
  geom_boxplot()

plottydata %>% 
  ggplot(aes(x = CQ, y = Phonation, color = Phonation)) +
  geom_boxplot() +
  facet_wrap(~language)

plottydata %>% 
  ggplot(aes(y = SQ, x = Phonation)) +
  geom_boxplot()

plottydata %>% 
  ggplot(aes(x = SQ, y = Phonation, color = Phonation)) +
  geom_boxplot() +
  facet_wrap(~language)
```


```{r}
# checking what "tone height" means again

all_data %>% 
  group_by(tone, tone_contour) %>% 
  count()

all_data %>% 
  group_by(tone, tone_contour, language_specific_tone, language) %>% 
  count()

all_data %>% 
  group_by(tone, tone_contour, language_specific_tone, tone_misc, language) %>% 
  count()
```


# this is me being an idiot:


```{r}
all_data %>% 
  ggplot(aes(x = peak_Vel, y = H1c)) +
  geom_point() +
  geom_smooth(method = "lm")
```

