---
title: "first_exploration"
author: "hssh"
format: html
---

```{r}
#| include: false
library(tidyverse)
library(fda)
```

```{r}
# From google gemini :/


# 1. Load data (header=TRUE to get those IDs)
data_df <- read.csv("egg_pulses.csv", header = TRUE, check.names = FALSE)
y_matrix <- as.matrix(data_df)
subject_ids <- colnames(y_matrix)

# 2. Set up your basis
time_points <- seq(0, 1, length.out = nrow(y_matrix))
basis_obj <- create.fourier.basis(c(0, 1), nbasis = 200)

# 3. Create the FD object with names
my_fd <- Data2fd(
  argvals = time_points, 
  y = y_matrix, 
  basisobj = basis_obj,
  fdnames = list("Time", "Subject_ID" = subject_ids, "Value"),
  lambda = 10E-12
)

# Now, if you look at the object, the IDs are baked in!
print(my_fd$fdnames$Subject_ID[1:10])


```

```{r}
# also from gen ai. boooo!!

pca_results <- pca.fd(my_fd, nharm = 200)

# View the PCA scores for the first 5 subjects
head(pca_results$scores) 
# Row names here will match your Subject IDs!

```

```{r}
plot(my_fd)
```

```{r}
plot.pca.fd(pca_results, harm = seq(1:10))
```

