---
title: "second_foray (lowpass!)"
author: "hssh"
format: html
---

Hey!!!!
Decompose this into R scripts, only using qmd for visualizations! Please!!

```{r}
#| include: false
library(tidyverse)
library(fda)
library(svglite)
```

```{r}
pulses <- read.csv("egg_pulses.csv", header = TRUE, check.names = FALSE)
pulses_matrix <- as.matrix(pulses)
ids <- colnames(pulses_matrix)

time <- seq(0, 1, length.out = nrow(pulses_matrix))
fourierBasis <- create.fourier.basis(c(0, 1), nbasis = 200)

functional_data_pulses <- Data2fd(
  argvals = time, 
  y = pulses_matrix, 
  basisobj = fourierBasis,
  fdnames = list("Time", "token_id" = ids, "Value"),
  lambda = 10E-12
)
```

```{r}
pca_results <- pca.fd(functional_data_pulses, nharm = 200)
```


```{r}
# svglite("all_pulses.svgz", width = 4, height = 2)
plot(functional_data_pulses)
# dev.off()
```

```{r}
# plot.pca.fd(pca_results, harm = seq(1:10))
plot.pca.fd(pca_results, harm = seq(1:4))
```

```{r}
# This cell is to save vector versions of the fpcs!

svglite("fpc_4.svg", width = 8, height = 5)
plot.pca.fd(pca_results, harm = 4)
dev.off()
```


```{r}
scores <- as.data.frame(pca_results$scores) %>%
  dplyr::select(1:4)
```

```{r}
all_data <- cbind(read_csv("voiceSauce_idd.csv"), scores)
```

```{r}
summary(all_data$V1)
sd(all_data$V1)
```

```{r}
all_data %>% 
  ggplot(aes(y = LPhon, fill = phonation)) +
  geom_bar()
```


```{r}
all_data %>% 
  ggplot(aes(y = V1, color = LPhon)) +
  geom_boxplot()
all_data %>% 
  ggplot(aes(y = V1, color = phonation)) +
  geom_boxplot()
V1_phonation_lm <- lm(V1 ~ phonation + language, data = all_data, na.action = na.exclude)
summary(V1_phonation_lm)
```

```{r}
all_data %>% 
  filter(V2 < 0.122) %>%
  ggplot(aes(x = V1, color = language)) +
  geom_boxplot() +
  facet_wrap(~phonation)
all_data %>% 
  filter(V2 < 0.122) %>%
  ggplot(aes(x = V2, color = language, fill = language)) +
  geom_density(alpha = 0.222) +
  facet_wrap(~phonation)
all_data %>% 
  ggplot(aes(y = V1, color = language)) +
  geom_boxplot()
# all_data %>% 
#   ggplot(aes(x = V1, fill = language, color = language)) +
#   geom_density(alpha = 0.25)
```

```{r}
all_data %>% 
  ggplot(aes(y = V3, color = phonation)) +
  geom_boxplot()
all_data %>% 
  ggplot(aes(y = V3, color = language)) +
  geom_boxplot()
```


```{r}
all_data %>% 
  ggplot(aes(y = V4, color = phonation)) +
  geom_boxplot()
all_data %>% 
  ggplot(aes(y = V4, color = language)) +
  geom_boxplot()
```

```{r}
# IN GUJARATI: V2 is kinda CPP?? / HNR?
# (that is also true of Zapotec! similar corr value of around 0.3222)
# Hmong isn't showing that unfortch!
all_data %>% 
  ggplot(aes(y = V2, x = CPP)) +
  geom_point() +
  geom_smooth(method = "lm")
  # facet_wrap(~ vowel_quality)
cor(all_data$V2, all_data$CPP)
modell <- lm(CPP ~ V2, data = all_data)
summary(modell)
sd(all_data$CPP)
```


```{r}
all_data %>% 
  ggplot(aes(x = V2, y = V3, color = phonation)) +
  geom_point()
all_data %>% 
  ggplot(aes(x = V2, y = V3, color = language)) +
  geom_point()
```

```{r}
all_data %>% 
  ggplot(aes(x = V1, y = CQ_H)) +
  geom_point(color = 'brown4') +
  geom_smooth(method = "lm", color = 'skyblue3')
all_data %>% 
  ggplot(aes(x = V1, y = CQ_H, color = phonation)) +
  geom_point(size = 0.67) +
  facet_wrap(~ language) +
  geom_smooth(method = 'lm', color = 'skyblue')
```

```{r}
all_data %>% 
  ggplot(aes(x = V1, y = H1c)) +
  geom_point(color = 'darkorange4') +
  geom_smooth(method = "lm", color = 'skyblue3')
all_data %>% 
  ggplot(aes(x = V1, y = H1c, color = phonation)) +
  geom_point(size = 0.67) +
  facet_wrap(~ language) +
  geom_smooth(method = 'lm', color = 'skyblue')
```


```{r}
all_data %>% 
  ggplot(aes(x = V4, y = strF0, color = phonation)) +
  geom_point() + 
  facet_wrap(~ language)
```




```{r}
all_data %>% 
  ggplot(aes(x = strF0, y = V4)) +
  geom_point() +
  facet_wrap(~ phonation)
phonLM <- lm(V4 ~ speaker_sex + strF0, data = all_data, na.action = na.exclude)
summary(phonLM)
```



```{r}
all_data %>% 
  # filter(phonation %in% c("Tense", "Creaky")) %>% 
  ggplot(aes(y = V1, color = phonation)) +
  geom_boxplot()

all_data %>% 
  # filter(phonation %in% c("Tense", "Creaky")) %>% 
  ggplot(aes(y = V2, color = phonation)) +
  geom_boxplot()

all_data %>% 
  ggplot(aes(x = V1, y = V2)) + # color = phonation found nothinggg
  geom_point() +
  geom_smooth()
  # + facet_wrap(~language)
# 
# This shape could be interestingg???? Whatever I'm done.

# stupidWhatever <- lm(V1 ~ phonation, data = all_data)
# summary(stupidWhatever)
```


